In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
# importing dataset
data = pd.read_csv("Social_Network_Ads.csv") 

In [3]:
# checking top 5 rows in data
data.head()

Age  EstimatedSalary  Purchased
0   19            19000          0
1   35            20000          0
2   26            43000          0
3   27            57000          0
4   19            76000          0

In [4]:
# Information about the data
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Age              400 non-null    int64
 1   EstimatedSalary  400 non-null    int64
 2   Purchased        400 non-null    int64
dtypes: int64(3)
memory usage: 9.5 KB


In [5]:
#check for missing values
data.isnull().sum() 

Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [6]:
# partitioning the data into features and labels as X and y respectively
X = data.iloc[:,:-1].values
y = data.iloc[:,-1].values

In [7]:
X

array([[    19,  19000],
       [    35,  20000],
       [    26,  43000],
       [    27,  57000],
       [    19,  76000],
       [    27,  58000],
       [    27,  84000],
       [    32, 150000],
       [    25,  33000],
       [    35,  65000],
       [    26,  80000],
       [    26,  52000],
       [    20,  86000],
       [    32,  18000],
       [    18,  82000],
       [    29,  80000],
       [    47,  25000],
       [    45,  26000],
       [    46,  28000],
       [    48,  29000],
       [    45,  22000],
       [    47,  49000],
       [    48,  41000],
       [    45,  22000],
       [    46,  23000],
       [    47,  20000],
       [    49,  28000],
       [    47,  30000],
       [    29,  43000],
       [    31,  18000],
       [    31,  74000],
       [    27, 137000],
       [    21,  16000],
       [    28,  44000],
       [    27,  90000],
       [    35,  27000],
       [    33,  28000],
       [    30,  49000],
       [    26,  72000],
       [    27,  31000],


In [8]:
y

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1,

In [9]:
# Splitting the Dataset 
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 5)

In [10]:
X_train

array([[    46,  23000],
       [    28,  44000],
       [    51,  23000],
       [    39, 106000],
       [    35,  50000],
       [    26,  86000],
       [    27,  84000],
       [    26,  80000],
       [    54, 108000],
       [    28,  59000],
       [    59,  42000],
       [    39,  42000],
       [    59,  88000],
       [    47,  51000],
       [    35,  73000],
       [    29,  75000],
       [    41,  60000],
       [    35,  60000],
       [    42, 149000],
       [    56, 133000],
       [    40,  61000],
       [    49,  28000],
       [    36,  50000],
       [    53,  82000],
       [    35,  22000],
       [    48,  33000],
       [    57,  60000],
       [    35,  88000],
       [    26,  15000],
       [    23,  20000],
       [    37,  52000],
       [    25,  79000],
       [    36, 126000],
       [    48,  35000],
       [    29,  80000],
       [    22,  18000],
       [    56,  60000],
       [    48, 141000],
       [    32, 117000],
       [    54,  70000],


In [11]:
y_train

array([1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1], d

There is no need of Encoder because data contains only numerical values not String.

In [12]:
# Scaling the features
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [13]:
X_train

array([[ 0.77063564, -1.37090753],
       [-0.95681661, -0.74731782],
       [ 1.25048349, -1.37090753],
       [ 0.09884866,  1.09375655],
       [-0.28502962, -0.56914934],
       [-1.14875575,  0.49986159],
       [-1.05278618,  0.44047209],
       [-1.14875575,  0.3216931 ],
       [ 1.5383922 ,  1.15314605],
       [-0.95681661, -0.3018966 ],
       [ 2.01824005, -0.80670732],
       [ 0.09884866, -0.80670732],
       [ 2.01824005,  0.55925109],
       [ 0.86660521, -0.53945459],
       [-0.28502962,  0.11382987],
       [-0.86084704,  0.17321936],
       [ 0.2907878 , -0.27220186],
       [-0.28502962, -0.27220186],
       [ 0.38675737,  2.37063071],
       [ 1.73033134,  1.89551474],
       [ 0.19481823, -0.24250711],
       [ 1.05854435, -1.22243379],
       [-0.18906005, -0.56914934],
       [ 1.44242263,  0.3810826 ],
       [-0.28502962, -1.40060228],
       [ 0.96257478, -1.07396005],
       [ 1.82630091, -0.27220186],
       [-0.28502962,  0.55925109],
       [-1.14875575,

In [14]:
# Training the model
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)

KNeighborsClassifier()

In [15]:
# Prediction on new sample data
classifier.predict(sc.transform([[56,22000]]))

array([1], dtype=int64)

In [16]:
# prediction on test data
pred = classifier.predict(X_test)
pred

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1,
       0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1], dtype=int64)

In [17]:
# Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score, r2_score
cm = confusion_matrix(y_test, pred)
print(cm)
print("Accuracy - ", accuracy_score(y_test, pred))
print("R2 Score - ", r2_score(y_test, pred))

[[62  4]
 [ 4 30]]
Accuracy -  0.92
R2 Score -  0.64349376114082


Here, R2 score is better than the logistic regression and SVM.