# Importing Libraries

In [225]:
import numpy as np
import pandas as pd

# Importing Dataset

In [226]:
dataset = pd.read_csv('../Dataset/wineQualityReds_data.csv')
# Removing the unnecessary column
dataset.drop(['Unnamed: 0'], axis = 1, inplace = True)
# seprating the dataset
X = X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1:].values

Data Preview

In [227]:
dataset.head()

fixed.acidity  volatile.acidity  citric.acid  residual.sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free.sulfur.dioxide  total.sulfur.dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [228]:
dataset.describe()

fixed.acidity  volatile.acidity  citric.acid  residual.sugar  \
count    1599.000000       1599.000000  1599.000000     1599.000000   
mean        8.319637          0.527821     0.270976        2.538806   
std         1.741096          0.179060     0.194801        1.409928   
min         4.600000          0.120000     0.000000        0.900000   
25%         7.100000          0.390000     0.090000        1.900000   
50%         7.900000          0.520000     0.260000        2.200000   
75%         9.200000          0.640000     0.420000        2.600000   
max        15.900000          1.580000     1.000000       15.500000   

         chlorides  free.sulfur.dioxide  total.sulfur.dioxide      density  \
count  1599.000000          1599.000000           1599.000000  1599.000000   
mean      0.087467            15.874922             46.467792     0.996747   
std       0.047065            10.460157             32.895324     0.001887   
min       0.012000             1.000000              6.000000     0.990070   
25%       0.070000             7.000000             22.000000     0.995600   
50%       0.079000            14.000000             38.000000     0.996750   
75%       0.090000            21.000000             62.000000     0.997835   
max       0.611000            72.000000            289.000000     1.003690   

                pH    sulphates      alcohol      quality  
count  1599.000000  1599.000000  1599.000000  1599.000000  
mean      3.311113     0.658149    10.422983     5.636023  
std       0.154386     0.169507     1.065668     0.807569  
min       2.740000     0.330000     8.400000     3.000000  
25%       3.210000     0.550000     9.500000     5.000000  
50%       3.310000     0.620000    10.200000     6.000000  
75%       3.400000     0.730000    11.100000     6.000000  
max       4.010000     2.000000    14.900000     8.000000

# Finding NULL values in dataset

In [229]:
dataset.isnull().values.any()
# No NULL record found in data

False

# Splitting the dataset

In [230]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)
# 80-20 split into train-test respectively

In [231]:
X_train

array([[ 9.9 ,  0.54,  0.45, ...,  3.39,  0.62,  9.4 ],
       [10.8 ,  0.26,  0.45, ...,  3.13,  0.54,  9.6 ],
       [ 9.9 ,  0.35,  0.55, ...,  3.26,  0.79, 10.6 ],
       ...,
       [ 7.9 ,  0.57,  0.31, ...,  3.29,  0.69,  9.5 ],
       [13.  ,  0.47,  0.49, ...,  3.3 ,  0.68, 12.7 ],
       [ 9.8 ,  0.98,  0.32, ...,  3.25,  0.48,  9.4 ]])

In [232]:
y_train

array([[5],
       [5],
       [5],
       ...,
       [6],
       [6],
       [5]], dtype=int64)

# Feature Scaling

In [233]:
from sklearn.preprocessing import StandardScaler
X_sc = StandardScaler()
y_sc = StandardScaler()
X_train = X_sc.fit_transform(X_train)
y_train = y_sc.fit_transform(y_train)

In [234]:
y_train

array([[-0.78933274],
       [-0.78933274],
       [-0.78933274],
       ...,
       [ 0.43141282],
       [ 0.43141282],
       [-0.78933274]])

# Fitting into Model

In [235]:
from sklearn.svm import SVR
regrassor = SVR(kernel = 'rbf')
regrassor.fit(X_train, y_train)

c:\users\pranjal\appdata\local\programs\python\python37\lib\site-packages\sklearn\utils\validation.py:985: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR()

# Prediction

In [236]:
y_pred = regrassor.predict(X_sc.transform(X_test))
y_pred = y_sc.inverse_transform(y_pred)

ValueError: Expected 2D array, got 1D array instead:
array=[-0.45171067 -0.50435534  1.72431945 -0.93218338  0.46786258 -0.58370757
 -0.67294184  0.33140658 -0.67516065 -0.72480452 -0.78451427 -0.23034499
 -0.04016597 -0.190164   -0.23531174  0.94750128  1.55199998 -0.29930531
 -0.15363902 -0.44034215  0.50143091 -0.47117466  0.08480602  0.17605571
 -0.30006733 -0.65437632 -0.55208142  1.47903157 -0.81878993  0.51078141
  0.2943675   0.3277672   0.05480392 -0.26129547  0.53727206  0.40635578
 -0.44334948  0.09326547  0.63865417  0.33637553 -0.54245503  1.24365157
  0.92469053  1.04034014  0.36300911 -0.77491376 -0.66464931  0.18438243
 -0.70470084  0.3771672  -0.98780784 -0.60344028  0.44499842  0.53142833
 -0.24509023 -0.49133587 -0.89410506 -0.59608725  1.33272293  0.03765856
 -0.76802522  0.31127073  0.54317498  0.21492838 -0.63100279  0.60196945
 -0.5857349  -0.69934607  0.82506001  0.51467718 -0.43893329 -0.49282165
 -0.72111951 -0.47775941 -0.02003783  0.49339468 -0.42933038 -0.67046876
 -0.58944128  1.22981831 -0.0762861  -0.66245752  0.12694715  0.31755284
 -0.1235457   0.03941733  0.40978445 -0.88958034 -0.31090144 -0.82274122
 -0.84888072 -0.65242707 -0.15104662 -0.48481671  0.54422115 -0.43893329
  1.03782032 -0.77093918 -0.09835291  0.36596909  1.41005819  0.25188198
  0.27206788  0.74340417 -0.51001623 -0.4654185  -0.51001623 -0.32426051
  0.35692135 -0.45237497  0.5022935  -0.92187056  1.07743354 -0.50948626
  0.26297385  0.3625049   0.16855567  1.3547425   0.41270674  0.08480602
 -0.64760264  0.24305322 -0.47728465 -0.77761331  0.62126097  1.24477587
 -0.82016106 -0.56836152  0.28568204  1.35924164 -0.49746381 -0.50711748
  0.45650874  0.25056205  0.53142419 -0.75820491  0.57675207 -0.6017005
  0.79577648 -0.7411918  -0.18978491 -0.69311638 -0.66464931 -0.33584751
 -0.54067547  0.11415076  1.07743354  1.12606582  0.86405901 -0.63487973
  0.52357922 -0.07436467 -0.32426051 -0.2015825   0.31208225 -0.05117997
 -0.57668742 -0.3455574   0.49900816  0.43311907  0.02370549 -0.1076811
  0.90111383 -0.53560158 -0.03231875 -0.65076312  0.27829405  0.63295919
 -0.31747888  0.53148194  0.36962762  0.02742196 -0.85036566  1.70431163
 -0.02315186  0.57470754  0.49352745  1.2964581   0.42172631 -0.79196752
 -0.85015996  1.67328799 -0.15263289  0.52334151  0.69872593 -0.61229224
 -0.09998163  0.27206788 -0.73367441  0.7262324   0.98780341 -0.1229918
 -0.00792385 -0.12625321 -0.71338012 -0.64768128 -0.78451427 -0.31682865
 -0.20323204 -0.80346462 -0.89920658  1.0723437  -0.6945531  -0.10899932
 -0.42323878 -0.89465927 -0.76908888  0.86476547  0.37997134 -0.43285921
 -0.0546106   0.38414389 -0.72537167  0.9162768  -0.84455798  0.12844327
  0.37369121  0.63641699  0.08551363 -0.78333737 -0.6892159   0.42024184
  0.74725467  0.1380516   0.11344181  0.31235884  0.65646753 -0.05893703
 -0.09730267 -0.39224468 -0.78713113  0.44944969 -0.66358832 -0.0667551
  1.00921783  0.25705532  0.94542109  1.64536242  0.74945005  0.63359945
 -0.07318704 -0.25364761 -0.71745528 -0.76035432  0.60460928 -0.75689248
 -0.01197289 -0.65800597 -0.68932445  0.53158968 -0.75449548 -0.41036697
 -0.79034526 -0.43629942 -0.17589866  0.00821923 -0.72258352 -0.88283062
 -0.65749936  0.40705494 -0.13798461  1.12458102 -0.34662333  0.06116916
 -0.41847134 -0.85420084 -0.5748767  -0.86078288  0.23745198  0.36571447
 -0.53620349  0.12630033 -0.506028    0.36747665  0.74292452  0.52343833
  0.98372546 -0.73716537  0.71672671  1.11167041 -0.68498397  1.01171013
  0.12630033  0.8877035   0.29840133 -0.71524031 -0.75150352 -0.57764763
  1.0791317   0.29483494  0.20404145 -0.44622643  0.73013143  0.04108032
 -0.41222495  0.33028178 -0.28501522 -0.86073597 -0.6709278  -0.61137945
  0.56011176 -0.90319187 -0.59704751 -0.18637747  0.6336578   0.3449099
 -0.44823705 -0.8109281  -0.40023664 -0.68947738 -0.16163056  0.75296611
 -0.60197242 -0.77093918 -0.70172965  0.73828884  0.39759734  0.79092564
 -0.31492865  1.0790801 ].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [238]:
y_test = y_test.flatten()
df = pd.DataFrame({'Predicted value': y_pred, 'Real Value': y_test})
df

Predicted value  Real Value
0          -0.451711           6
1          -0.504355           5
2           1.724319           7
3          -0.932183           6
4           0.467863           5
..               ...         ...
315         0.738289           6
316         0.397597           4
317         0.790926           5
318        -0.314929           4
319         1.079080           6

[320 rows x 2 columns]

# Checking the model accuracy with R2 score


In [237]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

-54.564221303651735