# Importing Libraries

In [153]:
import numpy as np
import pandas as pd

# Importing Dataset

In [156]:
dataset = pd.read_csv('../Dataset/salaries_data.csv')
# seprating the dataset
X = X = dataset.iloc[:, 1:-1].values
y = dataset.iloc[:, -1:].values

#here we exclude the Position column in our data

Data Preview

In [157]:
dataset.head()

Position  Level  Salary
0   Business Analyst      1   45000
1  Junior Consultant      2   50000
2  Senior Consultant      3   60000
3            Manager      4   80000
4    Country Manager      5  110000

In [143]:
dataset.describe()

Level          Salary
count  10.00000       10.000000
mean    5.50000   249500.000000
std     3.02765   299373.883668
min     1.00000    45000.000000
25%     3.25000    65000.000000
50%     5.50000   130000.000000
75%     7.75000   275000.000000
max    10.00000  1000000.000000

# Finding NULL values in dataset

In [144]:
dataset.isnull().values.any()
# No NULL record found in data

False

# Splitting the dataset

In [158]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [159]:
X_train

array([[ 5],
       [10],
       [ 2],
       [ 7],
       [ 8],
       [ 4],
       [ 1],
       [ 6]], dtype=int64)

In [160]:
y_train

array([[ 110000],
       [1000000],
       [  50000],
       [ 200000],
       [ 300000],
       [  80000],
       [  45000],
       [ 150000]], dtype=int64)

# Fitting into Model

In [161]:
from sklearn.tree import DecisionTreeRegressor
regressor = DecisionTreeRegressor(random_state = 0)
regressor.fit(X, y)

DecisionTreeRegressor(random_state=0)

# Prediction

In [162]:
y_pred = regressor.predict([[8.5]])

In [163]:
y_pred

array([300000.])